### PR TITLE
Issue #12: Delete Items from Shopping List

### LINKED ISSUE #12: 12. As a user, I want to be able to delete items from my shopping list so that my list isn’t cluttered with items I don’t want to buy in the future
## Summary
Users might make a mistake when entering an item, or may decide they won’t be buying a certain item again in the future. Allowing them to delete list items will help them keep their lists tidy.
 
## Acceptance criteria
- [x] The `ListItem` component renders a button that allows the user to delete an item from their list when clicked
- [x] Clicking the delete button prompts the user to confirm that they *really* want to delete the item
- [x]  The `deleteItem` function in `api/firebase.js` has been filled out, and deletes the item from the Firestore database

## Notes:
* Activating the “Delete” button should show a confirmation dialog. We want to give users a chance to confirm “destructive” actions.
* It might be tempting to create your own modal dialog component to handle confirmation, but modals are fraught with accessibility concerns, so consider using a simple [JavaScript confirm dialog](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm).

### PR DESCRIPTION
**Pull request by stacy-tech**
## Description

This PR allows users to delete items from their shopping list.

## Related Issue

- closes #12 

## Acceptance Criteria

- [x] The `ListItem` component renders a button that allows the user to delete an item from their list when clicked.
- [x] Clicking the delete button prompts the user to confirm that they really want to delete the item.
- [x] The `deleteItem` function in `api/firebase.js` has been filled out, and deletes the item from the Firestore database.

### Before

image_720

### After
image_720

image_720-1

image_720-2

## Testing Steps / QA Criteria

- Sign In to app using email account.
- Click on a list and navigate to `List` page.
- Click on the `Delete` button for the item you would like to delete. 
- A confirmation dialog box appears to confirm item to be deleted. 
- Click on `OK` to confirm. 
- A successful deletion message appears.

### CODE REVIEW

**Review by NickRoccodev11 — APPROVED** [review]
Very Nice, Works great, and I like the dynamic aria label as well!

**Review by dterceroparker — APPROVED** [review]
Great work! I tested it and it works well on my end 🌻

**Review by jtkabenni — APPROVED** [review]
Hey team, looks good but it would be a good idea while testing to also test some of the other flows that happen on this page. So I marked an item as purchased, and also searched for items in the search bar and the success message remained, which was a little strange. 
1. I deleted an item, then marked another as purchased, but the deleted message remained. If you are creating a success message for one action, I would consider making sure the behavior is the same for the other. 
Screenshot 2024-09-18 at 11 51 25 PM
2. If I search for something, the delete message remains.
Screenshot 2024-09-18 at 11 51 41 PM

Something you can consider is having the message time out after a few seconds, but just making sure the message reflects the most recent action is a good place to start.

**Comment by shuveksha-tuladhar** [comment]
Thank you @jtkabenni, for the suggestions. The code has been refactored to remove the message after 5 seconds and the message also gets removed when anything is typed on search items. Thank you.

**Pull request merged**
